# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oracle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sqlplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_number', models.BigIntegerField()),
                ('pid', models.BigIntegerField()),
                ('depth', models.BigIntegerField()),
                ('description', models.CharField(max_length=100, null=True)),
                ('object_owner', models.CharField(max_length=65, null=True)),
                ('object_name', models.CharField(max_length=65, null=True)),
                ('object_node', models.CharField(max_length=65, null=True)),
                ('cost', models.CharField(max_length=100, null=True)),
                ('cardinality', models.CharField(max_length=65, null=True)),
                ('bytes', models.CharField(max_length=65, null=True)),
                ('io_cost', models.CharField(max_length=65, null=True)),
                ('access_predicates', models.CharField(default='', max_length=1000, null=True)),
                ('filter_predicates', models.CharField(default='', max_length=1000, null=True)),
            ],
        ),
    ]
